project:
  type: website

website:
  title: "Shuwen Zhang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - file: about.qmd
        text: "About Me"
        
format:
  html:
    theme: lux
    toc: true

editor: visual

