project:
  type: website

website:
  title: "Shuwen Zhang"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    toc: true

editor: visual

